name: Run Azure Login with OpenID Connect
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read
      
jobs: 
  test-aad:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: 6b393b9e-cb47-482d-a2f7-3f2474bba6ab
          tenant-id: 36a6e4b2-e620-44c2-897b-22b1d394354a
          # Azure ADではなくAzure操作の場合は必要
          #subscription-id: a362f12c-0f8b-4c68-8dc9-c51c6fde1a56
          allow-no-subscriptions: true
  
#     - name: 'Run Azure CLI commands'
#       description: この場合はsubscription idの指定が必要
#       run: |
#           az account show
#           az group list
#           pwd
    - name: 'Run Azure AD commands'
      run: |
          az ad user list
          az ad group list
